[build]
  # Directory to change to before starting a build
  base = "apps/client"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  
  # Default build command - runs from apps/client directory
  command = "pnpm install && ./node_modules/.bin/tsc && ./node_modules/.bin/vite build"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # pnpm version
  PNPM_VERSION = "8"
  
  # Force clean build
  NETLIFY_CACHE_ID = "v2"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache static assets
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific settings
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NODE_ENV = "production"
